const paesi = [
  {
    "Paese": "Afghanistan",
    "Capitale": "Kabul",
    "Bandiera": "https://flagcdn.com/w320/af.png",
    "#": "1",
    "Continente": "Asia",
    "Superficie": "652,230",
    "Popolazione": "41,128,771",
    "Altitudine massima": "7492 m (Noshaq)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "19/11/1946",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "0.25",
    "Rank Democracy Index": "167",
    "ISO 2": "AF",
    "ISO 3": "AFG"
  },
  {
    "Paese": "Albania",
    "Capitale": "Tirana",
    "Bandiera": "https://flagcdn.com/w320/al.png",
    "#": "2",
    "Continente": "Europa",
    "Superficie": "28,748",
    "Popolazione": "2,842,321",
    "Altitudine massima": "2764 m (Monte Korab)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.2",
    "Rank Democracy Index": "66",
    "ISO 2": "AL",
    "ISO 3": "ALB"
  },
  {
    "Paese": "Algeria",
    "Capitale": "Algeri",
    "Bandiera": "https://flagcdn.com/w320/dz.png",
    "#": "3",
    "Continente": "Africa",
    "Superficie": "2,381,741",
    "Popolazione": "44,903,225",
    "Altitudine massima": "2908 m (Monte Tahat)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "08/10/1962",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.55",
    "Rank Democracy Index": "110",
    "ISO 2": "DZ",
    "ISO 3": "DZA"
  },
  {
    "Paese": "Andorra",
    "Capitale": "Andorra la Vella",
    "Bandiera": "https://flagcdn.com/w320/ad.png",
    "#": "4",
    "Continente": "Europa",
    "Superficie": "468",
    "Popolazione": "77,500",
    "Altitudine massima": "2942 m (Coma Pedrosa)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "28/07/1993",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "AD",
    "ISO 3": "AND"
  },
  {
    "Paese": "Angola",
    "Capitale": "Luanda",
    "Bandiera": "https://flagcdn.com/w320/ao.png",
    "#": "5",
    "Continente": "Africa",
    "Superficie": "1,246,700",
    "Popolazione": "35,588,956",
    "Altitudine massima": "2620 m (Monte Moco)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "01/12/1976",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.05",
    "Rank Democracy Index": "107",
    "ISO 2": "AO",
    "ISO 3": "AGO"
  },
  {
    "Paese": "Antigua e Barbuda",
    "Capitale": "Saint John's",
    "Bandiera": "https://flagcdn.com/w320/ag.png",
    "#": "6",
    "Continente": "Nord America",
    "Superficie": "442",
    "Popolazione": "93,763",
    "Altitudine massima": "402 m (Monte Obama)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "11/11/1981",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "AG",
    "ISO 3": "ATG"
  },
  {
    "Paese": "Arabia Saudita",
    "Capitale": "Riad",
    "Bandiera": "https://flagcdn.com/w320/sa.png",
    "#": "7",
    "Continente": "Asia",
    "Superficie": "2,149,690",
    "Popolazione": "36,408,820",
    "Altitudine massima": "3000 m (Jabal Sawda)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.08",
    "Rank Democracy Index": "148",
    "ISO 2": "SA",
    "ISO 3": "SAU"
  },
  {
    "Paese": "Argentina",
    "Capitale": "Buenos Aires",
    "Bandiera": "https://flagcdn.com/w320/ar.png",
    "#": "8",
    "Continente": "Sud America",
    "Superficie": "2,780,400",
    "Popolazione": "46,044,703",
    "Altitudine massima": "6961 m (Aconcagua)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.51",
    "Rank Democracy Index": "54",
    "ISO 2": "AR",
    "ISO 3": "ARG"
  },
  {
    "Paese": "Armenia",
    "Capitale": "Yerevan",
    "Bandiera": "https://flagcdn.com/w320/am.png",
    "#": "9",
    "Continente": "Asia",
    "Superficie": "29,743",
    "Popolazione": "2,780,469",
    "Altitudine massima": "4090 m (Monte Aragats)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.35",
    "Rank Democracy Index": "82",
    "ISO 2": "AM",
    "ISO 3": "ARM"
  },
  {
    "Paese": "Australia",
    "Capitale": "Canberra",
    "Bandiera": "https://flagcdn.com/w320/au.png",
    "#": "10",
    "Continente": "Oceania",
    "Superficie": "7,692,024",
    "Popolazione": "26,124,814",
    "Altitudine massima": "2228 m (Monte Kosciuszko)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "01/11/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.85",
    "Rank Democracy Index": "11",
    "ISO 2": "AU",
    "ISO 3": "AUS"
  },
  {
    "Paese": "Austria",
    "Capitale": "Vienna",
    "Bandiera": "https://flagcdn.com/w320/at.png",
    "#": "11",
    "Continente": "Europa",
    "Superficie": "83,871",
    "Popolazione": "8,939,617",
    "Altitudine massima": "3798 m (Grossglockner)",
    "Paesi confinanti": "8",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.28",
    "Rank Democracy Index": "19",
    "ISO 2": "AT",
    "ISO 3": "AUT"
  },
  {
    "Paese": "Azerbaigian",
    "Capitale": "Baku",
    "Bandiera": "https://flagcdn.com/w320/az.png",
    "#": "12",
    "Continente": "Asia/Europa",
    "Superficie": "86,600",
    "Popolazione": "10,175,016",
    "Altitudine massima": "4466 m (Bazardüzü Dağı)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.8",
    "Rank Democracy Index": "126",
    "ISO 2": "AZ",
    "ISO 3": "AZE"
  },
  {
    "Paese": "Bahamas",
    "Capitale": "Nassau",
    "Bandiera": "https://flagcdn.com/w320/bs.png",
    "#": "13",
    "Continente": "Nord America",
    "Superficie": "13,878",
    "Popolazione": "409,984",
    "Altitudine massima": "63 m (Monte Alvernia)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "18/09/1973",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "BS",
    "ISO 3": "BHS"
  },
  {
    "Paese": "Bahrein",
    "Capitale": "Manama",
    "Bandiera": "https://flagcdn.com/w320/bh.png",
    "#": "14",
    "Continente": "Asia",
    "Superficie": "765",
    "Popolazione": "1,501,635",
    "Altitudine massima": "134 m (Jabal ad Dukhan)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "21/09/1971",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.45",
    "Rank Democracy Index": "138",
    "ISO 2": "BH",
    "ISO 3": "BHR"
  },
  {
    "Paese": "Bangladesh",
    "Capitale": "Dacca",
    "Bandiera": "https://flagcdn.com/w320/bd.png",
    "#": "15",
    "Continente": "Asia",
    "Superficie": "147,570",
    "Popolazione": "171,186,372",
    "Altitudine massima": "1052 m (Saka Haphong)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "17/09/1974",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.44",
    "Rank Democracy Index": "100",
    "ISO 2": "BD",
    "ISO 3": "BGD"
  },
  {
    "Paese": "Barbados",
    "Capitale": "Bridgetown",
    "Bandiera": "https://flagcdn.com/w320/bb.png",
    "#": "16",
    "Continente": "Nord America",
    "Superficie": "430",
    "Popolazione": "281,635",
    "Altitudine massima": "340 m (Monte Hillaby)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "09/12/1966",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "BB",
    "ISO 3": "BRB"
  },
  {
    "Paese": "Belgio",
    "Capitale": "Bruxelles",
    "Bandiera": "https://flagcdn.com/w320/be.png",
    "#": "17",
    "Continente": "Europa",
    "Superficie": "30,528",
    "Popolazione": "11,676,661",
    "Altitudine massima": "694 m (Signal de Botrange)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "27/12/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.64",
    "Rank Democracy Index": "34",
    "ISO 2": "BE",
    "ISO 3": "BEL"
  },
  {
    "Paese": "Belize",
    "Capitale": "Belmopan",
    "Bandiera": "https://flagcdn.com/w320/bz.png",
    "#": "18",
    "Continente": "Nord America",
    "Superficie": "22,966",
    "Popolazione": "412,236",
    "Altitudine massima": "1124 m (Doyle's Delight)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "25/09/1981",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "BZ",
    "ISO 3": "BLZ"
  },
  {
    "Paese": "Benin",
    "Capitale": "Porto-Novo",
    "Bandiera": "https://flagcdn.com/w320/bj.png",
    "#": "19",
    "Continente": "Africa",
    "Superficie": "112,622",
    "Popolazione": "13,352,864",
    "Altitudine massima": "658 m (Monte Sokbaro)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.44",
    "Rank Democracy Index": "100",
    "ISO 2": "BJ",
    "ISO 3": "BEN"
  },
  {
    "Paese": "Bhutan",
    "Capitale": "Thimphu",
    "Bandiera": "https://flagcdn.com/w320/bt.png",
    "#": "20",
    "Continente": "Asia",
    "Superficie": "38,394",
    "Popolazione": "782,455",
    "Altitudine massima": "7570 m (Gangkhar Puensum)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "21/09/1971",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.65",
    "Rank Democracy Index": "79",
    "ISO 2": "BT",
    "ISO 3": "BTN"
  },
  {
    "Paese": "Bielorussia",
    "Capitale": "Minsk",
    "Bandiera": "https://flagcdn.com/w320/by.png",
    "#": "21",
    "Continente": "Europa",
    "Superficie": "207,600",
    "Popolazione": "9,200,617",
    "Altitudine massima": "345 m (Monte Dzyarzhynskaya)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.99",
    "Rank Democracy Index": "152",
    "ISO 2": "BY",
    "ISO 3": "BLR"
  },
  {
    "Paese": "Birmania (Myanmar)",
    "Capitale": "Naypyidaw",
    "Bandiera": "https://flagcdn.com/w320/mm.png",
    "#": "22",
    "Continente": "Asia",
    "Superficie": "676,578",
    "Popolazione": "54,179,306",
    "Altitudine massima": "5881 m (Hkakabo Razi)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "19/04/1948",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "0.96",
    "Rank Democracy Index": "166",
    "ISO 2": "MM",
    "ISO 3": "MMR"
  },
  {
    "Paese": "Bolivia",
    "Capitale": "Sucre",
    "Bandiera": "https://flagcdn.com/w320/bo.png",
    "#": "23",
    "Continente": "Sud America",
    "Superficie": "1,098,581",
    "Popolazione": "12,224,110",
    "Altitudine massima": "6542 m (Sajama)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "14/11/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.26",
    "Rank Democracy Index": "103",
    "ISO 2": "BO",
    "ISO 3": "BOL"
  },
  {
    "Paese": "Bosnia ed Erzegovina",
    "Capitale": "Sarajevo",
    "Bandiera": "https://flagcdn.com/w320/ba.png",
    "#": "24",
    "Continente": "Europa",
    "Superficie": "51,197",
    "Popolazione": "3,233,526",
    "Altitudine massima": "2386 m (Maglic)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "22/05/1992",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.06",
    "Rank Democracy Index": "88",
    "ISO 2": "BA",
    "ISO 3": "BIH"
  },
  {
    "Paese": "Botswana",
    "Capitale": "Gaborone",
    "Bandiera": "https://flagcdn.com/w320/bw.png",
    "#": "25",
    "Continente": "Africa",
    "Superficie": "581,730",
    "Popolazione": "2,630,296",
    "Altitudine massima": "1491 m (Otse Hill)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "17/10/1966",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.63",
    "Rank Democracy Index": "35",
    "ISO 2": "BW",
    "ISO 3": "BWA"
  },
  {
    "Paese": "Brasile",
    "Capitale": "Brasilia",
    "Bandiera": "https://flagcdn.com/w320/br.png",
    "#": "26",
    "Continente": "Sud America",
    "Superficie": "8,515,767",
    "Popolazione": "215,313,498",
    "Altitudine massima": "2995 m (Pico da Neblina)",
    "Paesi confinanti": "10",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.49",
    "Rank Democracy Index": "57",
    "ISO 2": "BR",
    "ISO 3": "BRA"
  },
  {
    "Paese": "Brunei",
    "Capitale": "Bandar Seri Begawan",
    "Bandiera": "https://flagcdn.com/w320/bn.png",
    "#": "27",
    "Continente": "Asia",
    "Superficie": "5,765",
    "Popolazione": "449,002",
    "Altitudine massima": "1850 m (Bukit Pagon)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "21/09/1984",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "BN",
    "ISO 3": "BRN"
  },
  {
    "Paese": "Bulgaria",
    "Capitale": "Sofia",
    "Bandiera": "https://flagcdn.com/w320/bg.png",
    "#": "28",
    "Continente": "Europa",
    "Superficie": "110,879",
    "Popolazione": "6,447,710",
    "Altitudine massima": "2925 m (Musala)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.34",
    "Rank Democracy Index": "61",
    "ISO 2": "BG",
    "ISO 3": "BGR"
  },
  {
    "Paese": "Burkina Faso",
    "Capitale": "Ouagadougou",
    "Bandiera": "https://flagcdn.com/w320/bf.png",
    "#": "29",
    "Continente": "Africa",
    "Superficie": "274,200",
    "Popolazione": "22,673,762",
    "Altitudine massima": "749 m (Tena Kourou)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.55",
    "Rank Democracy Index": "137",
    "ISO 2": "BF",
    "ISO 3": "BFA"
  },
  {
    "Paese": "Burundi",
    "Capitale": "Gitega",
    "Bandiera": "https://flagcdn.com/w320/bi.png",
    "#": "30",
    "Continente": "Africa",
    "Superficie": "27,834",
    "Popolazione": "12,889,576",
    "Altitudine massima": "2684 m (Monte Heha)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "18/09/1962",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.13",
    "Rank Democracy Index": "144",
    "ISO 2": "BI",
    "ISO 3": "BDI"
  },
  {
    "Paese": "Cambogia",
    "Capitale": "Phnom Penh",
    "Bandiera": "https://flagcdn.com/w320/kh.png",
    "#": "31",
    "Continente": "Asia",
    "Superficie": "181,035",
    "Popolazione": "16,767,851",
    "Altitudine massima": "1813 m (Phnom Aural)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.94",
    "Rank Democracy Index": "123",
    "ISO 2": "KH",
    "ISO 3": "KHM"
  },
  {
    "Paese": "Camerun",
    "Capitale": "Yaoundé",
    "Bandiera": "https://flagcdn.com/w320/cm.png",
    "#": "32",
    "Continente": "Africa",
    "Superficie": "475,442",
    "Popolazione": "27,914,536",
    "Altitudine massima": "4040 m (Monte Camerun)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.56",
    "Rank Democracy Index": "136",
    "ISO 2": "CM",
    "ISO 3": "CMR"
  },
  {
    "Paese": "Canada",
    "Capitale": "Ottawa",
    "Bandiera": "https://flagcdn.com/w320/ca.png",
    "#": "33",
    "Continente": "Nord America",
    "Superficie": "9,984,670",
    "Popolazione": "38,929,902",
    "Altitudine massima": "5959 m (Monte Logan)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "09/11/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.69",
    "Rank Democracy Index": "14",
    "ISO 2": "CA",
    "ISO 3": "CAN"
  },
  {
    "Paese": "Capo Verde",
    "Capitale": "Praia",
    "Bandiera": "https://flagcdn.com/w320/cv.png",
    "#": "34",
    "Continente": "Africa",
    "Superficie": "4,033",
    "Popolazione": "593,149",
    "Altitudine massima": "2829 m (Pico do Fogo)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "16/09/1975",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.58",
    "Rank Democracy Index": "37",
    "ISO 2": "CV",
    "ISO 3": "CPV"
  },
  {
    "Paese": "Ciad",
    "Capitale": "N'Djamena",
    "Bandiera": "https://flagcdn.com/w320/td.png",
    "#": "35",
    "Continente": "Africa",
    "Superficie": "1,284,000",
    "Popolazione": "17,723,315",
    "Altitudine massima": "3445 m (Emi Koussi)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.89",
    "Rank Democracy Index": "158",
    "ISO 2": "TD",
    "ISO 3": "TCD"
  },
  {
    "Paese": "Cile",
    "Capitale": "Santiago del Cile",
    "Bandiera": "https://flagcdn.com/w320/cl.png",
    "#": "36",
    "Continente": "Sud America",
    "Superficie": "756,102",
    "Popolazione": "19,603,733",
    "Altitudine massima": "6893 m (Ojos del Salado)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.83",
    "Rank Democracy Index": "29",
    "ISO 2": "CL",
    "ISO 3": "CHL"
  },
  {
    "Paese": "Cina",
    "Capitale": "Pechino",
    "Bandiera": "https://flagcdn.com/w320/cn.png",
    "#": "37",
    "Continente": "Asia",
    "Superficie": "9,596,961",
    "Popolazione": "1,411,750,000",
    "Altitudine massima": "8848 m (Monte Everest)",
    "Paesi confinanti": "14",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.11",
    "Rank Democracy Index": "145",
    "ISO 2": "CN",
    "ISO 3": "CHN"
  },
  {
    "Paese": "Cipro",
    "Capitale": "Nicosia",
    "Bandiera": "https://flagcdn.com/w320/cy.png",
    "#": "38",
    "Continente": "Europa/Asia",
    "Superficie": "9,251",
    "Popolazione": "1,251,488",
    "Altitudine massima": "1952 m (Monte Olimpo)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.38",
    "Rank Democracy Index": "40",
    "ISO 2": "CY",
    "ISO 3": "CYP"
  },
  {
    "Paese": "Colombia",
    "Capitale": "Bogotà",
    "Bandiera": "https://flagcdn.com/w320/co.png",
    "#": "39",
    "Continente": "Sud America",
    "Superficie": "1,141,748",
    "Popolazione": "51,874,024",
    "Altitudine massima": "5700 m (Pico Cristóbal Colón)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "05/11/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.35",
    "Rank Democracy Index": "60",
    "ISO 2": "CO",
    "ISO 3": "COL"
  },
  {
    "Paese": "Comore",
    "Capitale": "Moroni",
    "Bandiera": "https://flagcdn.com/w320/km.png",
    "#": "40",
    "Continente": "Africa",
    "Superficie": "1,862",
    "Popolazione": "836,774",
    "Altitudine massima": "2360 m (Monte Karthala)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "12/11/1975",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.84",
    "Rank Democracy Index": "124",
    "ISO 2": "KM",
    "ISO 3": "COM"
  },
  {
    "Paese": "Corea del Nord",
    "Capitale": "Pyongyang",
    "Bandiera": "https://flagcdn.com/w320/kp.png",
    "#": "41",
    "Continente": "Asia",
    "Superficie": "120,540",
    "Popolazione": "26,059,203",
    "Altitudine massima": "2744 m (Monte Paektu)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "17/09/1991",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.08",
    "Rank Democracy Index": "165",
    "ISO 2": "KP",
    "ISO 3": "PRK"
  },
  {
    "Paese": "Corea del Sud",
    "Capitale": "Seul",
    "Bandiera": "https://flagcdn.com/w320/kr.png",
    "#": "42",
    "Continente": "Asia",
    "Superficie": "100,210",
    "Popolazione": "51,744,876",
    "Altitudine massima": "1950 m (Hallasan)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "17/09/1991",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.75",
    "Rank Democracy Index": "32",
    "ISO 2": "KR",
    "ISO 3": "KOR"
  },
  {
    "Paese": "Costa d'Avorio",
    "Capitale": "Yamoussoukro",
    "Bandiera": "https://flagcdn.com/w320/ci.png",
    "#": "43",
    "Continente": "Africa",
    "Superficie": "322,463",
    "Popolazione": "28,160,543",
    "Altitudine massima": "1752 m (Monte Nimba)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.22",
    "Rank Democracy Index": "105",
    "ISO 2": "CI",
    "ISO 3": "CIV"
  },
  {
    "Paese": "Costa Rica",
    "Capitale": "San José",
    "Bandiera": "https://flagcdn.com/w320/cr.png",
    "#": "44",
    "Continente": "Nord America",
    "Superficie": "51,100",
    "Popolazione": "5,180,000",
    "Altitudine massima": "3819 m (Cerro Chirripó)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "02/11/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.29",
    "Rank Democracy Index": "18",
    "ISO 2": "CR",
    "ISO 3": "CRI"
  },
  {
    "Paese": "Croazia",
    "Capitale": "Zagabria",
    "Bandiera": "https://flagcdn.com/w320/hr.png",
    "#": "45",
    "Continente": "Europa",
    "Superficie": "56,594",
    "Popolazione": "3,871,833",
    "Altitudine massima": "1831 m (Dinara)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "22/05/1992",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.5",
    "Rank Democracy Index": "56",
    "ISO 2": "HR",
    "ISO 3": "HRV"
  },
  {
    "Paese": "Cuba",
    "Capitale": "L'Avana",
    "Bandiera": "https://flagcdn.com/w320/cu.png",
    "#": "46",
    "Continente": "Nord America",
    "Superficie": "109,884",
    "Popolazione": "11,089,511",
    "Altitudine massima": "1974 m (Pico Turquino)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.58",
    "Rank Democracy Index": "135",
    "ISO 2": "CU",
    "ISO 3": "CUB"
  },
  {
    "Paese": "Danimarca",
    "Capitale": "Copenaghen",
    "Bandiera": "https://flagcdn.com/w320/dk.png",
    "#": "47",
    "Continente": "Europa",
    "Superficie": "43,094",
    "Popolazione": "5,935,000",
    "Altitudine massima": "170 m (Møllehøj)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9.28",
    "Rank Democracy Index": "7",
    "ISO 2": "DK",
    "ISO 3": "DNK"
  },
  {
    "Paese": "Dominica",
    "Capitale": "Roseau",
    "Bandiera": "https://flagcdn.com/w320/dm.png",
    "#": "48",
    "Continente": "Nord America",
    "Superficie": "751",
    "Popolazione": "72,412",
    "Altitudine massima": "1447 m (Morne Diablotins)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "18/12/1978",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "DM",
    "ISO 3": "DMA"
  },
  {
    "Paese": "Ecuador",
    "Capitale": "Quito",
    "Bandiera": "https://flagcdn.com/w320/ec.png",
    "#": "49",
    "Continente": "Sud America",
    "Superficie": "283,561",
    "Popolazione": "18,001,000",
    "Altitudine massima": "6267 m (Chimborazo)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "21/12/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.24",
    "Rank Democracy Index": "85",
    "ISO 2": "EC",
    "ISO 3": "ECU"
  },
  {
    "Paese": "Egitto",
    "Capitale": "Il Cairo",
    "Bandiera": "https://flagcdn.com/w320/eg.png",
    "#": "50",
    "Continente": "Africa",
    "Superficie": "1,002,450",
    "Popolazione": "110,990,103",
    "Altitudine massima": "2629 m (Monte Caterina)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.79",
    "Rank Democracy Index": "128",
    "ISO 2": "EG",
    "ISO 3": "EGY"
  },
  {
    "Paese": "El Salvador",
    "Capitale": "San Salvador",
    "Bandiera": "https://flagcdn.com/w320/sv.png",
    "#": "51",
    "Continente": "Nord America",
    "Superficie": "21,041",
    "Popolazione": "6,336,392",
    "Altitudine massima": "2730 m (Cerro El Pital)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.61",
    "Rank Democracy Index": "95",
    "ISO 2": "SV",
    "ISO 3": "SLV"
  },
  {
    "Paese": "Emirati Arabi Uniti",
    "Capitale": "Abu Dhabi",
    "Bandiera": "https://flagcdn.com/w320/ae.png",
    "#": "52",
    "Continente": "Asia",
    "Superficie": "83,600",
    "Popolazione": "9,441,129",
    "Altitudine massima": "1934 m (Jebel Jais)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "09/12/1971",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.07",
    "Rank Democracy Index": "119",
    "ISO 2": "AE",
    "ISO 3": "ARE"
  },
  {
    "Paese": "Eritrea",
    "Capitale": "Asmara",
    "Bandiera": "https://flagcdn.com/w320/er.png",
    "#": "53",
    "Continente": "Africa",
    "Superficie": "117,600",
    "Popolazione": "3,684,032",
    "Altitudine massima": "3018 m (Monte Emba Soira)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "28/05/1993",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.97",
    "Rank Democracy Index": "153",
    "ISO 2": "ER",
    "ISO 3": "ERI"
  },
  {
    "Paese": "Estonia",
    "Capitale": "Tallinn",
    "Bandiera": "https://flagcdn.com/w320/ee.png",
    "#": "54",
    "Continente": "Europa",
    "Superficie": "45,227",
    "Popolazione": "1,331,796",
    "Altitudine massima": "318 m (Suur Munamägi)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "17/09/1991",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.13",
    "Rank Democracy Index": "21",
    "ISO 2": "EE",
    "ISO 3": "EST"
  },
  {
    "Paese": "eSwatini (Swaziland)",
    "Capitale": "Mbabane",
    "Bandiera": "https://flagcdn.com/w320/sz.png",
    "#": "55",
    "Continente": "Africa",
    "Superficie": "17,364",
    "Popolazione": "1,192,271",
    "Altitudine massima": "1862 m (Emlembe)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "24/09/1968",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.6",
    "Rank Democracy Index": "134",
    "ISO 2": "SZ",
    "ISO 3": "SWZ"
  },
  {
    "Paese": "Etiopia",
    "Capitale": "Addis Abeba",
    "Bandiera": "https://flagcdn.com/w320/et.png",
    "#": "56",
    "Continente": "Africa",
    "Superficie": "1,104,300",
    "Popolazione": "123,379,924",
    "Altitudine massima": "4550 m (Ras Dascian)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "13/11/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.24",
    "Rank Democracy Index": "116",
    "ISO 2": "ET",
    "ISO 3": "ETH"
  },
  {
    "Paese": "Figi",
    "Capitale": "Suva",
    "Bandiera": "https://flagcdn.com/w320/fj.png",
    "#": "57",
    "Continente": "Oceania",
    "Superficie": "18,274",
    "Popolazione": "926,276",
    "Altitudine massima": "1324 m (Monte Tomanivi)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "13/10/1970",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.39",
    "Rank Democracy Index": "81",
    "ISO 2": "FJ",
    "ISO 3": "FJI"
  },
  {
    "Paese": "Filippine",
    "Capitale": "Manila",
    "Bandiera": "https://flagcdn.com/w320/ph.png",
    "#": "58",
    "Continente": "Asia",
    "Superficie": "300,000",
    "Popolazione": "115,559,009",
    "Altitudine massima": "2954 m (Monte Apo)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.63",
    "Rank Democracy Index": "51",
    "ISO 2": "PH",
    "ISO 3": "PHL"
  },
  {
    "Paese": "Finlandia",
    "Capitale": "Helsinki",
    "Bandiera": "https://flagcdn.com/w320/fi.png",
    "#": "59",
    "Continente": "Europa",
    "Superficie": "338,424",
    "Popolazione": "5,556,102",
    "Altitudine massima": "1324 m (Halti)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9.3",
    "Rank Democracy Index": "6",
    "ISO 2": "FI",
    "ISO 3": "FIN"
  },
  {
    "Paese": "Francia",
    "Capitale": "Parigi",
    "Bandiera": "https://flagcdn.com/w320/fr.png",
    "#": "60",
    "Continente": "Europa",
    "Superficie": "643,801",
    "Popolazione": "68,035,000",
    "Altitudine massima": "4810 m (Monte Bianco)",
    "Paesi confinanti": "8",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.99",
    "Rank Democracy Index": "26",
    "ISO 2": "FR",
    "ISO 3": "FRA"
  },
  {
    "Paese": "Gabon",
    "Capitale": "Libreville",
    "Bandiera": "https://flagcdn.com/w320/ga.png",
    "#": "61",
    "Continente": "Africa",
    "Superficie": "267,667",
    "Popolazione": "2,388,992",
    "Altitudine massima": "1070 m (Monte Bengoué)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.18",
    "Rank Democracy Index": "143",
    "ISO 2": "GA",
    "ISO 3": "GAB"
  },
  {
    "Paese": "Gambia",
    "Capitale": "Banjul",
    "Bandiera": "https://flagcdn.com/w320/gm.png",
    "#": "62",
    "Continente": "Africa",
    "Superficie": "11,300",
    "Popolazione": "2,705,992",
    "Altitudine massima": "53 m (Red Rock)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "21/09/1965",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.47",
    "Rank Democracy Index": "99",
    "ISO 2": "GM",
    "ISO 3": "GMB"
  },
  {
    "Paese": "Georgia",
    "Capitale": "Tbilisi",
    "Bandiera": "https://flagcdn.com/w320/ge.png",
    "#": "63",
    "Continente": "Asia/Europa",
    "Superficie": "69,700",
    "Popolazione": "3,712,502",
    "Altitudine massima": "5193 m (Monte Shkhara)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "31/07/1992",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.7",
    "Rank Democracy Index": "94",
    "ISO 2": "GE",
    "ISO 3": "GEO"
  },
  {
    "Paese": "Germania",
    "Capitale": "Berlino",
    "Bandiera": "https://flagcdn.com/w320/de.png",
    "#": "64",
    "Continente": "Europa",
    "Superficie": "357,588",
    "Popolazione": "83,852,168",
    "Altitudine massima": "2962 m (Zugspitze)",
    "Paesi confinanti": "9",
    "Data adesione ONU": "18/09/1973",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.73",
    "Rank Democracy Index": "13",
    "ISO 2": "DE",
    "ISO 3": "DEU"
  },
  {
    "Paese": "Ghana",
    "Capitale": "Accra",
    "Bandiera": "https://flagcdn.com/w320/gh.png",
    "#": "65",
    "Continente": "Africa",
    "Superficie": "238,533",
    "Popolazione": "33,475,870",
    "Altitudine massima": "885 m (Monte Afadjato)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "08/03/1957",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.24",
    "Rank Democracy Index": "65",
    "ISO 2": "GH",
    "ISO 3": "GHA"
  },
  {
    "Paese": "Giamaica",
    "Capitale": "Kingston",
    "Bandiera": "https://flagcdn.com/w320/jm.png",
    "#": "66",
    "Continente": "Nord America",
    "Superficie": "10,991",
    "Popolazione": "2,827,377",
    "Altitudine massima": "2256 m (Blue Mountain Peak)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "18/09/1962",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.74",
    "Rank Democracy Index": "49",
    "ISO 2": "JM",
    "ISO 3": "JAM"
  },
  {
    "Paese": "Giappone",
    "Capitale": "Tokyo",
    "Bandiera": "https://flagcdn.com/w320/jp.png",
    "#": "67",
    "Continente": "Asia",
    "Superficie": "377,975",
    "Popolazione": "125,124,989",
    "Altitudine massima": "3776 m (Monte Fuji)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "18/12/1956",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.48",
    "Rank Democracy Index": "16",
    "ISO 2": "JP",
    "ISO 3": "JPN"
  },
  {
    "Paese": "Gibuti",
    "Capitale": "Gibuti",
    "Bandiera": "https://flagcdn.com/w320/dj.png",
    "#": "68",
    "Continente": "Africa",
    "Superficie": "23,200",
    "Popolazione": "1,120,849",
    "Altitudine massima": "2028 m (Mousa Ali)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "20/09/1977",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.7",
    "Rank Democracy Index": "132",
    "ISO 2": "DJ",
    "ISO 3": "DJI"
  },
  {
    "Paese": "Giordania",
    "Capitale": "Amman",
    "Bandiera": "https://flagcdn.com/w320/jo.png",
    "#": "69",
    "Continente": "Asia",
    "Superficie": "89,342",
    "Popolazione": "11,285,869",
    "Altitudine massima": "1854 m (Jabal Umm ad Dami)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.28",
    "Rank Democracy Index": "115",
    "ISO 2": "JO",
    "ISO 3": "JOR"
  },
  {
    "Paese": "Grecia",
    "Capitale": "Atene",
    "Bandiera": "https://flagcdn.com/w320/gr.png",
    "#": "70",
    "Continente": "Europa",
    "Superficie": "131,957",
    "Popolazione": "10,482,487",
    "Altitudine massima": "2917 m (Monte Olimpo)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "25/10/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.07",
    "Rank Democracy Index": "25",
    "ISO 2": "GR",
    "ISO 3": "GRC"
  },
  {
    "Paese": "Grenada",
    "Capitale": "Saint George's",
    "Bandiera": "https://flagcdn.com/w320/gd.png",
    "#": "71",
    "Continente": "Nord America",
    "Superficie": "344",
    "Popolazione": "125,438",
    "Altitudine massima": "840 m (Monte Saint Catherine)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "17/09/1974",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "GD",
    "ISO 3": "GRD"
  },
  {
    "Paese": "Guatemala",
    "Capitale": "Città del Guatemala",
    "Bandiera": "https://flagcdn.com/w320/gt.png",
    "#": "72",
    "Continente": "Nord America",
    "Superficie": "108,889",
    "Popolazione": "17,357,886",
    "Altitudine massima": "4220 m (Vulcano Tajumulco)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "21/11/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.55",
    "Rank Democracy Index": "97",
    "ISO 2": "GT",
    "ISO 3": "GTM"
  },
  {
    "Paese": "Guinea",
    "Capitale": "Conakry",
    "Bandiera": "https://flagcdn.com/w320/gn.png",
    "#": "73",
    "Continente": "Africa",
    "Superficie": "245,857",
    "Popolazione": "13,859,341",
    "Altitudine massima": "1752 m (Monte Nimba)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "12/12/1958",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.04",
    "Rank Democracy Index": "149",
    "ISO 2": "GN",
    "ISO 3": "GIN"
  },
  {
    "Paese": "Guinea Equatoriale",
    "Capitale": "Malabo",
    "Bandiera": "https://flagcdn.com/w320/gq.png",
    "#": "74",
    "Continente": "Africa",
    "Superficie": "28,051",
    "Popolazione": "1,674,908",
    "Altitudine massima": "3003 m (Pico Basile)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "12/11/1968",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.92",
    "Rank Democracy Index": "156",
    "ISO 2": "GQ",
    "ISO 3": "GNQ"
  },
  {
    "Paese": "Guinea-Bissau",
    "Capitale": "Bissau",
    "Bandiera": "https://flagcdn.com/w320/gw.png",
    "#": "75",
    "Continente": "Africa",
    "Superficie": "36,125",
    "Popolazione": "2,105,566",
    "Altitudine massima": "300 m (Località senza nome nel NE)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "17/09/1974",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.03",
    "Rank Democracy Index": "150",
    "ISO 2": "GW",
    "ISO 3": "GNB"
  },
  {
    "Paese": "Guyana",
    "Capitale": "Georgetown",
    "Bandiera": "https://flagcdn.com/w320/gy.png",
    "#": "76",
    "Continente": "Sud America",
    "Superficie": "214,969",
    "Popolazione": "808,726",
    "Altitudine massima": "2835 m (Monte Roraima)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "20/09/1966",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.11",
    "Rank Democracy Index": "69",
    "ISO 2": "GY",
    "ISO 3": "GUY"
  },
  {
    "Paese": "Haiti",
    "Capitale": "Port-au-Prince",
    "Bandiera": "https://flagcdn.com/w320/ht.png",
    "#": "77",
    "Continente": "Nord America",
    "Superficie": "27,750",
    "Popolazione": "11,584,996",
    "Altitudine massima": "2680 m (Pic la Selle)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.74",
    "Rank Democracy Index": "131",
    "ISO 2": "HT",
    "ISO 3": "HTI"
  },
  {
    "Paese": "Honduras",
    "Capitale": "Tegucigalpa",
    "Bandiera": "https://flagcdn.com/w320/hn.png",
    "#": "78",
    "Continente": "Nord America",
    "Superficie": "112,492",
    "Popolazione": "10,432,860",
    "Altitudine massima": "2870 m (Cerro Las Minas)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "17/12/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.98",
    "Rank Democracy Index": "90",
    "ISO 2": "HN",
    "ISO 3": "HND"
  },
  {
    "Paese": "India",
    "Capitale": "Nuova Delhi",
    "Bandiera": "https://flagcdn.com/w320/in.png",
    "#": "79",
    "Continente": "Asia",
    "Superficie": "3,287,263",
    "Popolazione": "1,428,627,663",
    "Altitudine massima": "8586 m (Kanchenjunga)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "30/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.29",
    "Rank Democracy Index": "41",
    "ISO 2": "IN",
    "ISO 3": "IND"
  },
  {
    "Paese": "Indonesia",
    "Capitale": "Giacarta",
    "Bandiera": "https://flagcdn.com/w320/id.png",
    "#": "80",
    "Continente": "Asia",
    "Superficie": "1,904,569",
    "Popolazione": "275,501,339",
    "Altitudine massima": "4884 m (Puncak Jaya)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "28/09/1950",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.44",
    "Rank Democracy Index": "59",
    "ISO 2": "ID",
    "ISO 3": "IDN"
  },
  {
    "Paese": "Iran",
    "Capitale": "Teheran",
    "Bandiera": "https://flagcdn.com/w320/ir.png",
    "#": "81",
    "Continente": "Asia",
    "Superficie": "1,648,195",
    "Popolazione": "88,550,570",
    "Altitudine massima": "5610 m (Monte Damavand)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.96",
    "Rank Democracy Index": "154",
    "ISO 2": "IR",
    "ISO 3": "IRN"
  },
  {
    "Paese": "Iraq",
    "Capitale": "Baghdad",
    "Bandiera": "https://flagcdn.com/w320/iq.png",
    "#": "82",
    "Continente": "Asia",
    "Superficie": "438,317",
    "Popolazione": "44,496,122",
    "Altitudine massima": "3611 m (Cheekha Dar)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "21/12/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.8",
    "Rank Democracy Index": "126",
    "ISO 2": "IQ",
    "ISO 3": "IRQ"
  },
  {
    "Paese": "Irlanda",
    "Capitale": "Dublino",
    "Bandiera": "https://flagcdn.com/w320/ie.png",
    "#": "83",
    "Continente": "Europa",
    "Superficie": "70,273",
    "Popolazione": "5,123,536",
    "Altitudine massima": "1038 m (Carrauntoohil)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9.19",
    "Rank Democracy Index": "8",
    "ISO 2": "IE",
    "ISO 3": "IRL"
  },
  {
    "Paese": "Islanda",
    "Capitale": "Reykjavík",
    "Bandiera": "https://flagcdn.com/w320/is.png",
    "#": "84",
    "Continente": "Europa",
    "Superficie": "103,000",
    "Popolazione": "376,248",
    "Altitudine massima": "2110 m (Hvannadalshnúkur)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "19/11/1946",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9.38",
    "Rank Democracy Index": "4",
    "ISO 2": "IS",
    "ISO 3": "ISL"
  },
  {
    "Paese": "Isole Marshall",
    "Capitale": "Majuro",
    "Bandiera": "https://flagcdn.com/w320/mh.png",
    "#": "85",
    "Continente": "Oceania",
    "Superficie": "181",
    "Popolazione": "41,569",
    "Altitudine massima": "10 m (Località senza nome a Likiep)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "17/09/1991",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "MH",
    "ISO 3": "MHL"
  },
  {
    "Paese": "Isole Salomone",
    "Capitale": "Honiara",
    "Bandiera": "https://flagcdn.com/w320/sb.png",
    "#": "86",
    "Continente": "Oceania",
    "Superficie": "28,896",
    "Popolazione": "724,273",
    "Altitudine massima": "2332 m (Monte Popomanaseu)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "19/09/1978",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "SB",
    "ISO 3": "SLB"
  },
  {
    "Paese": "Israele",
    "Capitale": "Gerusalemme",
    "Bandiera": "https://flagcdn.com/w320/il.png",
    "#": "87",
    "Continente": "Asia",
    "Superficie": "20,770",
    "Popolazione": "9,757,490",
    "Altitudine massima": "2814 m (Monte Hermon)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "11/05/1949",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.8",
    "Rank Democracy Index": "31",
    "ISO 2": "IL",
    "ISO 3": "ISR"
  },
  {
    "Paese": "Italia",
    "Capitale": "Roma",
    "Bandiera": "https://flagcdn.com/w320/it.png",
    "#": "88",
    "Continente": "Europa",
    "Superficie": "301,340",
    "Popolazione": "58,850,717",
    "Altitudine massima": "4810 m (Monte Bianco)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.58",
    "Rank Democracy Index": "37",
    "ISO 2": "IT",
    "ISO 3": "ITA"
  },
  {
    "Paese": "Kazakistan",
    "Capitale": "Astana",
    "Bandiera": "https://flagcdn.com/w320/kz.png",
    "#": "89",
    "Continente": "Asia/Europa",
    "Superficie": "2,724,900",
    "Popolazione": "19,621,972",
    "Altitudine massima": "7010 m (Khan Tengri)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.08",
    "Rank Democracy Index": "118",
    "ISO 2": "KZ",
    "ISO 3": "KAZ"
  },
  {
    "Paese": "Kenya",
    "Capitale": "Nairobi",
    "Bandiera": "https://flagcdn.com/w320/ke.png",
    "#": "90",
    "Continente": "Africa",
    "Superficie": "580,367",
    "Popolazione": "54,027,487",
    "Altitudine massima": "5199 m (Monte Kenya)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "16/12/1963",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.05",
    "Rank Democracy Index": "89",
    "ISO 2": "KE",
    "ISO 3": "KEN"
  },
  {
    "Paese": "Kirghizistan",
    "Capitale": "Biškek",
    "Bandiera": "https://flagcdn.com/w320/kg.png",
    "#": "91",
    "Continente": "Asia",
    "Superficie": "199,951",
    "Popolazione": "6,802,300",
    "Altitudine massima": "7439 m (Jengish Chokusu)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.52",
    "Rank Democracy Index": "111",
    "ISO 2": "KG",
    "ISO 3": "KGZ"
  },
  {
    "Paese": "Kiribati",
    "Capitale": "Tarawa Sud",
    "Bandiera": "https://flagcdn.com/w320/ki.png",
    "#": "92",
    "Continente": "Oceania",
    "Superficie": "811",
    "Popolazione": "131,232",
    "Altitudine massima": "81 m (Località senza nome a Banaba)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "14/09/1999",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "KI",
    "ISO 3": "KIR"
  },
  {
    "Paese": "Kuwait",
    "Capitale": "Madinat al-Kuwait",
    "Bandiera": "https://flagcdn.com/w320/kw.png",
    "#": "93",
    "Continente": "Asia",
    "Superficie": "17,818",
    "Popolazione": "4,268,873",
    "Altitudine massima": "306 m (Mutla Ridge)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "14/05/1963",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.78",
    "Rank Democracy Index": "130",
    "ISO 2": "KW",
    "ISO 3": "KWT"
  },
  {
    "Paese": "Laos",
    "Capitale": "Vientiane",
    "Bandiera": "https://flagcdn.com/w320/la.png",
    "#": "94",
    "Continente": "Asia",
    "Superficie": "236,800",
    "Popolazione": "7,529,475",
    "Altitudine massima": "2817 m (Phou Bia)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.71",
    "Rank Democracy Index": "160",
    "ISO 2": "LA",
    "ISO 3": "LAO"
  },
  {
    "Paese": "Lesotho",
    "Capitale": "Maseru",
    "Bandiera": "https://flagcdn.com/w320/ls.png",
    "#": "95",
    "Continente": "Africa",
    "Superficie": "30,355",
    "Popolazione": "2,306,000",
    "Altitudine massima": "3482 m (Thabana Ntlenyana)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "17/10/1966",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.06",
    "Rank Democracy Index": "70",
    "ISO 2": "LS",
    "ISO 3": "LSO"
  },
  {
    "Paese": "Lettonia",
    "Capitale": "Riga",
    "Bandiera": "https://flagcdn.com/w320/lv.png",
    "#": "96",
    "Continente": "Europa",
    "Superficie": "64,589",
    "Popolazione": "1,883,008",
    "Altitudine massima": "312 m (Gaizinkalns)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "17/09/1991",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.66",
    "Rank Democracy Index": "33",
    "ISO 2": "LV",
    "ISO 3": "LVA"
  },
  {
    "Paese": "Libano",
    "Capitale": "Beirut",
    "Bandiera": "https://flagcdn.com/w320/lb.png",
    "#": "97",
    "Continente": "Asia",
    "Superficie": "10,452",
    "Popolazione": "5,489,739",
    "Altitudine massima": "3088 m (Qurnat as Sawda')",
    "Paesi confinanti": "2",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.56",
    "Rank Democracy Index": "109",
    "ISO 2": "LB",
    "ISO 3": "LBN"
  },
  {
    "Paese": "Liberia",
    "Capitale": "Monrovia",
    "Bandiera": "https://flagcdn.com/w320/lr.png",
    "#": "98",
    "Continente": "Africa",
    "Superficie": "111,369",
    "Popolazione": "5,302,681",
    "Altitudine massima": "1440 m (Monte Wuteve)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "02/11/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.57",
    "Rank Democracy Index": "80",
    "ISO 2": "LR",
    "ISO 3": "LBR"
  },
  {
    "Paese": "Libia",
    "Capitale": "Tripoli",
    "Bandiera": "https://flagcdn.com/w320/ly.png",
    "#": "99",
    "Continente": "Africa",
    "Superficie": "1,759,540",
    "Popolazione": "6,812,341",
    "Altitudine massima": "2267 m (Bikku Bitti)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.31",
    "Rank Democracy Index": "140",
    "ISO 2": "LY",
    "ISO 3": "LBY"
  },
  {
    "Paese": "Liechtenstein",
    "Capitale": "Vaduz",
    "Bandiera": "https://flagcdn.com/w320/li.png",
    "#": "100",
    "Continente": "Europa",
    "Superficie": "160",
    "Popolazione": "39,308",
    "Altitudine massima": "2599 m (Grauspitz)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "18/09/1990",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "LI",
    "ISO 3": "LIE"
  },
  {
    "Paese": "Lituania",
    "Capitale": "Vilnius",
    "Bandiera": "https://flagcdn.com/w320/lt.png",
    "#": "101",
    "Continente": "Europa",
    "Superficie": "65,300",
    "Popolazione": "2,833,042",
    "Altitudine massima": "294 m (Aukštojas)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "17/09/1991",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.59",
    "Rank Democracy Index": "36",
    "ISO 2": "LT",
    "ISO 3": "LTU"
  },
  {
    "Paese": "Lussemburgo",
    "Capitale": "Lussemburgo",
    "Bandiera": "https://flagcdn.com/w320/lu.png",
    "#": "102",
    "Continente": "Europa",
    "Superficie": "2,586",
    "Popolazione": "660,809",
    "Altitudine massima": "560 m (Kneiff)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.88",
    "Rank Democracy Index": "10",
    "ISO 2": "LU",
    "ISO 3": "LUX"
  },
  {
    "Paese": "Macedonia del Nord",
    "Capitale": "Skopje",
    "Bandiera": "https://flagcdn.com/w320/mk.png",
    "#": "103",
    "Continente": "Europa",
    "Superficie": "25,713",
    "Popolazione": "2,058,447",
    "Altitudine massima": "2764 m (Monte Korab)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "08/04/1993",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.28",
    "Rank Democracy Index": "62",
    "ISO 2": "MK",
    "ISO 3": "MKD"
  },
  {
    "Paese": "Madagascar",
    "Capitale": "Antananarivo",
    "Bandiera": "https://flagcdn.com/w320/mg.png",
    "#": "104",
    "Continente": "Africa",
    "Superficie": "587,041",
    "Popolazione": "29,611,714",
    "Altitudine massima": "2876 m (Maromokotro)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.33",
    "Rank Democracy Index": "83",
    "ISO 2": "MG",
    "ISO 3": "MDG"
  },
  {
    "Paese": "Malawi",
    "Capitale": "Lilongwe",
    "Bandiera": "https://flagcdn.com/w320/mw.png",
    "#": "105",
    "Continente": "Africa",
    "Superficie": "118,484",
    "Popolazione": "20,405,317",
    "Altitudine massima": "3002 m (Monte Mulanje)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "01/12/1964",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.85",
    "Rank Democracy Index": "76",
    "ISO 2": "MW",
    "ISO 3": "MWI"
  },
  {
    "Paese": "Malaysia",
    "Capitale": "Kuala Lumpur",
    "Bandiera": "https://flagcdn.com/w320/my.png",
    "#": "106",
    "Continente": "Asia",
    "Superficie": "329,847",
    "Popolazione": "33,938,221",
    "Altitudine massima": "4095 m (Monte Kinabalu)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "17/09/1957",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.11",
    "Rank Democracy Index": "44",
    "ISO 2": "MY",
    "ISO 3": "MYS"
  },
  {
    "Paese": "Maldive",
    "Capitale": "Malé",
    "Bandiera": "https://flagcdn.com/w320/mv.png",
    "#": "107",
    "Continente": "Asia",
    "Superficie": "298",
    "Popolazione": "523,781",
    "Altitudine massima": "5 m (Mount Willigili)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "21/09/1965",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "MV",
    "ISO 3": "MDV"
  },
  {
    "Paese": "Mali",
    "Capitale": "Bamako",
    "Bandiera": "https://flagcdn.com/w320/ml.png",
    "#": "108",
    "Continente": "Africa",
    "Superficie": "1,240,192",
    "Popolazione": "22,593,590",
    "Altitudine massima": "1155 m (Monte Hombori)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "28/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.4",
    "Rank Democracy Index": "139",
    "ISO 2": "ML",
    "ISO 3": "MLI"
  },
  {
    "Paese": "Malta",
    "Capitale": "La Valletta",
    "Bandiera": "https://flagcdn.com/w320/mt.png",
    "#": "109",
    "Continente": "Europa",
    "Superficie": "316",
    "Popolazione": "533,286",
    "Altitudine massima": "253 m (Ta' Dmejrek)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "01/12/1964",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.93",
    "Rank Democracy Index": "27",
    "ISO 2": "MT",
    "ISO 3": "MLT"
  },
  {
    "Paese": "Marocco",
    "Capitale": "Rabat",
    "Bandiera": "https://flagcdn.com/w320/ma.png",
    "#": "110",
    "Continente": "Africa",
    "Superficie": "446,550",
    "Popolazione": "37,457,929",
    "Altitudine massima": "4165 m (Jebel Toubkal)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "12/11/1956",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.97",
    "Rank Democracy Index": "91",
    "ISO 2": "MA",
    "ISO 3": "MAR"
  },
  {
    "Paese": "Mauritania",
    "Capitale": "Nouakchott",
    "Bandiera": "https://flagcdn.com/w320/mr.png",
    "#": "111",
    "Continente": "Africa",
    "Superficie": "1,030,700",
    "Popolazione": "4,736,139",
    "Altitudine massima": "915 m (Kediet ej Jill)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "27/10/1961",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.96",
    "Rank Democracy Index": "108",
    "ISO 2": "MR",
    "ISO 3": "MRT"
  },
  {
    "Paese": "Mauritius",
    "Capitale": "Port Louis",
    "Bandiera": "https://flagcdn.com/w320/mu.png",
    "#": "112",
    "Continente": "Africa",
    "Superficie": "2,040",
    "Popolazione": "1,262,523",
    "Altitudine massima": "828 m (Piton de la Petite Rivière Noire)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "24/04/1968",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.23",
    "Rank Democracy Index": "20",
    "ISO 2": "MU",
    "ISO 3": "MUS"
  },
  {
    "Paese": "Messico",
    "Capitale": "Città del Messico",
    "Bandiera": "https://flagcdn.com/w320/mx.png",
    "#": "113",
    "Continente": "Nord America",
    "Superficie": "1,964,375",
    "Popolazione": "128,455,567",
    "Altitudine massima": "5636 m (Pico de Orizaba)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "07/11/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.32",
    "Rank Democracy Index": "84",
    "ISO 2": "MX",
    "ISO 3": "MEX"
  },
  {
    "Paese": "Moldavia",
    "Capitale": "Chișinău",
    "Bandiera": "https://flagcdn.com/w320/md.png",
    "#": "114",
    "Continente": "Europa",
    "Superficie": "33,846",
    "Popolazione": "2,538,894",
    "Altitudine massima": "430 m (Dealul Bălănești)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.04",
    "Rank Democracy Index": "71",
    "ISO 2": "MD",
    "ISO 3": "MDA"
  },
  {
    "Paese": "Monaco",
    "Capitale": "Monaco",
    "Bandiera": "https://flagcdn.com/w320/mc.png",
    "#": "115",
    "Continente": "Europa",
    "Superficie": "2.08",
    "Popolazione": "36,297",
    "Altitudine massima": "161 m (Chemin des Révoires)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "28/05/1993",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "MC",
    "ISO 3": "MCO"
  },
  {
    "Paese": "Mongolia",
    "Capitale": "Ulan Bator",
    "Bandiera": "https://flagcdn.com/w320/mn.png",
    "#": "116",
    "Continente": "Asia",
    "Superficie": "1,564,116",
    "Popolazione": "3,398,366",
    "Altitudine massima": "4374 m (Punta Khüiten)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "27/10/1961",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.53",
    "Rank Democracy Index": "53",
    "ISO 2": "MN",
    "ISO 3": "MNG"
  },
  {
    "Paese": "Montenegro",
    "Capitale": "Podgorica",
    "Bandiera": "https://flagcdn.com/w320/me.png",
    "#": "117",
    "Continente": "Europa",
    "Superficie": "13,812",
    "Popolazione": "617,213",
    "Altitudine massima": "2534 m (Zla Kolata)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "28/06/2006",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.73",
    "Rank Democracy Index": "50",
    "ISO 2": "ME",
    "ISO 3": "MNE"
  },
  {
    "Paese": "Mozambico",
    "Capitale": "Maputo",
    "Bandiera": "https://flagcdn.com/w320/mz.png",
    "#": "118",
    "Continente": "Africa",
    "Superficie": "799,380",
    "Popolazione": "32,977,066",
    "Altitudine massima": "2436 m (Monte Binga)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "16/09/1975",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.38",
    "Rank Democracy Index": "113",
    "ISO 2": "MZ",
    "ISO 3": "MOZ"
  },
  {
    "Paese": "Namibia",
    "Capitale": "Windhoek",
    "Bandiera": "https://flagcdn.com/w320/na.png",
    "#": "119",
    "Continente": "Africa",
    "Superficie": "824,292",
    "Popolazione": "2,567,012",
    "Altitudine massima": "2606 m (Konigstein)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "23/04/1990",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.48",
    "Rank Democracy Index": "58",
    "ISO 2": "NA",
    "ISO 3": "NAM"
  },
  {
    "Paese": "Nauru",
    "Capitale": "Yaren",
    "Bandiera": "https://flagcdn.com/w320/nr.png",
    "#": "120",
    "Continente": "Oceania",
    "Superficie": "21",
    "Popolazione": "12,668",
    "Altitudine massima": "65 m (Command Ridge)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "14/09/1999",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "NR",
    "ISO 3": "NRU"
  },
  {
    "Paese": "Nepal",
    "Capitale": "Kathmandu",
    "Bandiera": "https://flagcdn.com/w320/np.png",
    "#": "121",
    "Continente": "Asia",
    "Superficie": "147,181",
    "Popolazione": "30,547,580",
    "Altitudine massima": "8848 m (Monte Everest)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.6",
    "Rank Democracy Index": "96",
    "ISO 2": "NP",
    "ISO 3": "NPL"
  },
  {
    "Paese": "Nicaragua",
    "Capitale": "Managua",
    "Bandiera": "https://flagcdn.com/w320/ni.png",
    "#": "122",
    "Continente": "Nord America",
    "Superficie": "130,370",
    "Popolazione": "6,948,392",
    "Altitudine massima": "2107 m (Mogoton)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.09",
    "Rank Democracy Index": "147",
    "ISO 2": "NI",
    "ISO 3": "NIC"
  },
  {
    "Paese": "Niger",
    "Capitale": "Niamey",
    "Bandiera": "https://flagcdn.com/w320/ne.png",
    "#": "123",
    "Continente": "Africa",
    "Superficie": "1,267,000",
    "Popolazione": "26,208,158",
    "Altitudine massima": "2022 m (Monte Idoukal-n-Taghès)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.26",
    "Rank Democracy Index": "141",
    "ISO 2": "NE",
    "ISO 3": "NER"
  },
  {
    "Paese": "Nigeria",
    "Capitale": "Abuja",
    "Bandiera": "https://flagcdn.com/w320/ng.png",
    "#": "124",
    "Continente": "Africa",
    "Superficie": "923,768",
    "Popolazione": "218,541,212",
    "Altitudine massima": "2419 m (Chappal Waddi)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "07/10/1960",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.16",
    "Rank Democracy Index": "106",
    "ISO 2": "NG",
    "ISO 3": "NGA"
  },
  {
    "Paese": "Norvegia",
    "Capitale": "Oslo",
    "Bandiera": "https://flagcdn.com/w320/no.png",
    "#": "125",
    "Continente": "Europa",
    "Superficie": "385,207",
    "Popolazione": "5,457,127",
    "Altitudine massima": "2469 m (Galdhøpiggen)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "27/11/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9.81",
    "Rank Democracy Index": "1",
    "ISO 2": "NO",
    "ISO 3": "NOR"
  },
  {
    "Paese": "Nuova Zelanda",
    "Capitale": "Wellington",
    "Bandiera": "https://flagcdn.com/w320/nz.png",
    "#": "126",
    "Continente": "Oceania",
    "Superficie": "268,021",
    "Popolazione": "5,124,100",
    "Altitudine massima": "3724 m (Monte Cook)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9.61",
    "Rank Democracy Index": "2",
    "ISO 2": "NZ",
    "ISO 3": "NZL"
  },
  {
    "Paese": "Oman",
    "Capitale": "Mascate",
    "Bandiera": "https://flagcdn.com/w320/om.png",
    "#": "127",
    "Continente": "Asia",
    "Superficie": "309,500",
    "Popolazione": "4,576,298",
    "Altitudine massima": "3009 m (Jabal Shams)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "07/10/1971",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.05",
    "Rank Democracy Index": "120",
    "ISO 2": "OM",
    "ISO 3": "OMN"
  },
  {
    "Paese": "Paesi Bassi",
    "Capitale": "Amsterdam",
    "Bandiera": "https://flagcdn.com/w320/nl.png",
    "#": "128",
    "Continente": "Europa",
    "Superficie": "41,543",
    "Popolazione": "17,700,000",
    "Altitudine massima": "322 m (Vaalserberg)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "10/12/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9",
    "Rank Democracy Index": "9",
    "ISO 2": "NL",
    "ISO 3": "NLD"
  },
  {
    "Paese": "Pakistan",
    "Capitale": "Islamabad",
    "Bandiera": "https://flagcdn.com/w320/pk.png",
    "#": "129",
    "Continente": "Asia",
    "Superficie": "796,095",
    "Popolazione": "235,824,862",
    "Altitudine massima": "8611 m (K2)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "30/09/1947",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.84",
    "Rank Democracy Index": "124",
    "ISO 2": "PK",
    "ISO 3": "PAK"
  },
  {
    "Paese": "Palau",
    "Capitale": "Ngerulmud",
    "Bandiera": "https://flagcdn.com/w320/pw.png",
    "#": "130",
    "Continente": "Oceania",
    "Superficie": "459",
    "Popolazione": "18,055",
    "Altitudine massima": "242 m (Monte Ngerchelchuus)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "15/12/1994",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "PW",
    "ISO 3": "PLW"
  },
  {
    "Paese": "Panama",
    "Capitale": "Panama",
    "Bandiera": "https://flagcdn.com/w320/pa.png",
    "#": "131",
    "Continente": "Nord America",
    "Superficie": "75,420",
    "Popolazione": "4,408,581",
    "Altitudine massima": "3475 m (Vulcano Barú)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "13/11/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.84",
    "Rank Democracy Index": "47",
    "ISO 2": "PA",
    "ISO 3": "PAN"
  },
  {
    "Paese": "Papua Nuova Guinea",
    "Capitale": "Port Moresby",
    "Bandiera": "https://flagcdn.com/w320/pg.png",
    "#": "132",
    "Continente": "Oceania",
    "Superficie": "462,840",
    "Popolazione": "10,142,612",
    "Altitudine massima": "4509 m (Monte Wilhelm)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "10/10/1975",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.97",
    "Rank Democracy Index": "73",
    "ISO 2": "PG",
    "ISO 3": "PNG"
  },
  {
    "Paese": "Paraguay",
    "Capitale": "Asunción",
    "Bandiera": "https://flagcdn.com/w320/py.png",
    "#": "133",
    "Continente": "Sud America",
    "Superficie": "406,752",
    "Popolazione": "6,780,744",
    "Altitudine massima": "842 m (Cerro Peró)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.92",
    "Rank Democracy Index": "75",
    "ISO 2": "PY",
    "ISO 3": "PRY"
  },
  {
    "Paese": "Perù",
    "Capitale": "Lima",
    "Bandiera": "https://flagcdn.com/w320/pe.png",
    "#": "134",
    "Continente": "Sud America",
    "Superficie": "1,285,216",
    "Popolazione": "34,049,588",
    "Altitudine massima": "6768 m (Huascarán)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "31/10/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.69",
    "Rank Democracy Index": "78",
    "ISO 2": "PE",
    "ISO 3": "PER"
  },
  {
    "Paese": "Polonia",
    "Capitale": "Varsavia",
    "Bandiera": "https://flagcdn.com/w320/pl.png",
    "#": "135",
    "Continente": "Europa",
    "Superficie": "312,685",
    "Popolazione": "37,672,367",
    "Altitudine massima": "2499 m (Rysy)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.4",
    "Rank Democracy Index": "39",
    "ISO 2": "PL",
    "ISO 3": "POL"
  },
  {
    "Paese": "Portogallo",
    "Capitale": "Lisbona",
    "Bandiera": "https://flagcdn.com/w320/pt.png",
    "#": "136",
    "Continente": "Europa",
    "Superficie": "92,212",
    "Popolazione": "10,379,007",
    "Altitudine massima": "2351 m (Ponta do Pico)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.08",
    "Rank Democracy Index": "23",
    "ISO 2": "PT",
    "ISO 3": "PRT"
  },
  {
    "Paese": "Qatar",
    "Capitale": "Doha",
    "Bandiera": "https://flagcdn.com/w320/qa.png",
    "#": "137",
    "Continente": "Asia",
    "Superficie": "11,586",
    "Popolazione": "2,695,122",
    "Altitudine massima": "103 m (Qurayn Abu al Bawl)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "21/09/1971",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.17",
    "Rank Democracy Index": "117",
    "ISO 2": "QA",
    "ISO 3": "QAT"
  },
  {
    "Paese": "Regno Unito",
    "Capitale": "Londra",
    "Bandiera": "https://flagcdn.com/w320/gb.png",
    "#": "138",
    "Continente": "Europa",
    "Superficie": "242,495",
    "Popolazione": "67,081,234",
    "Altitudine massima": "1345 m (Ben Nevis)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.34",
    "Rank Democracy Index": "17",
    "ISO 2": "GB",
    "ISO 3": "GBR"
  },
  {
    "Paese": "Repubblica Ceca",
    "Capitale": "Praga",
    "Bandiera": "https://flagcdn.com/w320/cz.png",
    "#": "139",
    "Continente": "Europa",
    "Superficie": "78,867",
    "Popolazione": "10,516,707",
    "Altitudine massima": "1603 m (Sněžka)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "19/01/1993",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.08",
    "Rank Democracy Index": "23",
    "ISO 2": "CZ",
    "ISO 3": "CZE"
  },
  {
    "Paese": "Repubblica Centrafricana",
    "Capitale": "Bangui",
    "Bandiera": "https://flagcdn.com/w320/cf.png",
    "#": "140",
    "Continente": "Africa",
    "Superficie": "622,984",
    "Popolazione": "5,579,144",
    "Altitudine massima": "1420 m (Monte Ngaoui)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.18",
    "Rank Democracy Index": "164",
    "ISO 2": "CF",
    "ISO 3": "CAF"
  },
  {
    "Paese": "Repubblica del Congo",
    "Capitale": "Brazzaville",
    "Bandiera": "https://flagcdn.com/w320/cg.png",
    "#": "141",
    "Continente": "Africa",
    "Superficie": "342,000",
    "Popolazione": "5,970,000",
    "Altitudine massima": "1020 m (Monte Nabeba)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.79",
    "Rank Democracy Index": "128",
    "ISO 2": "CG",
    "ISO 3": "COG"
  },
  {
    "Paese": "Repubblica Democratica del Congo",
    "Capitale": "Kinshasa",
    "Bandiera": "https://flagcdn.com/w320/cd.png",
    "#": "142",
    "Continente": "Africa",
    "Superficie": "2,344,858",
    "Popolazione": "99,010,212",
    "Altitudine massima": "5109 m (Monte Stanley)",
    "Paesi confinanti": "9",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.92",
    "Rank Democracy Index": "156",
    "ISO 2": "CD",
    "ISO 3": "COD"
  },
  {
    "Paese": "Repubblica Dominicana",
    "Capitale": "Santo Domingo",
    "Bandiera": "https://flagcdn.com/w320/do.png",
    "#": "143",
    "Continente": "Nord America",
    "Superficie": "48,671",
    "Popolazione": "11,228,821",
    "Altitudine massima": "3098 m (Pico Duarte)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.62",
    "Rank Democracy Index": "52",
    "ISO 2": "DO",
    "ISO 3": "DOM"
  },
  {
    "Paese": "Romania",
    "Capitale": "Bucarest",
    "Bandiera": "https://flagcdn.com/w320/ro.png",
    "#": "144",
    "Continente": "Europa",
    "Superficie": "238,391",
    "Popolazione": "19,038,000",
    "Altitudine massima": "2544 m (Monte Moldoveanu)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.99",
    "Rank Democracy Index": "72",
    "ISO 2": "RO",
    "ISO 3": "ROU"
  },
  {
    "Paese": "Ruanda",
    "Capitale": "Kigali",
    "Bandiera": "https://flagcdn.com/w320/rw.png",
    "#": "145",
    "Continente": "Africa",
    "Superficie": "26,338",
    "Popolazione": "13,776,698",
    "Altitudine massima": "4507 m (Monte Karisimbi)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "18/09/1962",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.34",
    "Rank Democracy Index": "114",
    "ISO 2": "RW",
    "ISO 3": "RWA"
  },
  {
    "Paese": "Russia",
    "Capitale": "Mosca",
    "Bandiera": "https://flagcdn.com/w320/ru.png",
    "#": "146",
    "Continente": "Europa/Asia",
    "Superficie": "17,098,242",
    "Popolazione": "144,444,359",
    "Altitudine massima": "5642 m (Monte Elbrus)",
    "Paesi confinanti": "14",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.03",
    "Rank Democracy Index": "150",
    "ISO 2": "RU",
    "ISO 3": "RUS"
  },
  {
    "Paese": "Saint Kitts e Nevis",
    "Capitale": "Basseterre",
    "Bandiera": "https://flagcdn.com/w320/kn.png",
    "#": "147",
    "Continente": "Nord America",
    "Superficie": "261",
    "Popolazione": "47,657",
    "Altitudine massima": "1156 m (Monte Liamuiga)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "23/09/1983",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "KN",
    "ISO 3": "KNA"
  },
  {
    "Paese": "Saint Lucia",
    "Capitale": "Castries",
    "Bandiera": "https://flagcdn.com/w320/lc.png",
    "#": "148",
    "Continente": "Nord America",
    "Superficie": "616",
    "Popolazione": "180,000",
    "Altitudine massima": "950 m (Monte Gimie)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "18/09/1979",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "LC",
    "ISO 3": "LCA"
  },
  {
    "Paese": "Saint Vincent e Grenadine",
    "Capitale": "Kingstown",
    "Bandiera": "https://flagcdn.com/w320/vc.png",
    "#": "149",
    "Continente": "Nord America",
    "Superficie": "389",
    "Popolazione": "103,974",
    "Altitudine massima": "1234 m (La Soufrière)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "16/09/1980",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "VC",
    "ISO 3": "VCT"
  },
  {
    "Paese": "Samoa",
    "Capitale": "Apia",
    "Bandiera": "https://flagcdn.com/w320/ws.png",
    "#": "150",
    "Continente": "Oceania",
    "Superficie": "2,831",
    "Popolazione": "202,310",
    "Altitudine massima": "1857 m (Monte Silisili)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "15/12/1976",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "WS",
    "ISO 3": "WSM"
  },
  {
    "Paese": "San Marino",
    "Capitale": "San Marino",
    "Bandiera": "https://flagcdn.com/w320/sm.png",
    "#": "151",
    "Continente": "Europa",
    "Superficie": "61",
    "Popolazione": "33,660",
    "Altitudine massima": "749 m (Monte Titano)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "SM",
    "ISO 3": "SMR"
  },
  {
    "Paese": "São Tomé e Príncipe",
    "Capitale": "São Tomé",
    "Bandiera": "https://flagcdn.com/w320/st.png",
    "#": "152",
    "Continente": "Africa",
    "Superficie": "964",
    "Popolazione": "227,380",
    "Altitudine massima": "2024 m (Pico de São Tomé)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "16/09/1975",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "ST",
    "ISO 3": "STP"
  },
  {
    "Paese": "Senegal",
    "Capitale": "Dakar",
    "Bandiera": "https://flagcdn.com/w320/sn.png",
    "#": "153",
    "Continente": "Africa",
    "Superficie": "196,722",
    "Popolazione": "17,316,449",
    "Altitudine massima": "648 m (Località senza nome vicino a Nepen Diakha)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "28/09/1960",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.93",
    "Rank Democracy Index": "74",
    "ISO 2": "SN",
    "ISO 3": "SEN"
  },
  {
    "Paese": "Serbia",
    "Capitale": "Belgrado",
    "Bandiera": "https://flagcdn.com/w320/rs.png",
    "#": "154",
    "Continente": "Europa",
    "Superficie": "88,361",
    "Popolazione": "6,647,003",
    "Altitudine massima": "2169 m (Midžor)",
    "Paesi confinanti": "8",
    "Data adesione ONU": "01/11/2000",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.26",
    "Rank Democracy Index": "64",
    "ISO 2": "RS",
    "ISO 3": "SRB"
  },
  {
    "Paese": "Seychelles",
    "Capitale": "Victoria",
    "Bandiera": "https://flagcdn.com/w320/sc.png",
    "#": "155",
    "Continente": "Africa",
    "Superficie": "455",
    "Popolazione": "107,135",
    "Altitudine massima": "905 m (Morne Seychellois)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "21/09/1976",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "SC",
    "ISO 3": "SYC"
  },
  {
    "Paese": "Sierra Leone",
    "Capitale": "Freetown",
    "Bandiera": "https://flagcdn.com/w320/sl.png",
    "#": "156",
    "Continente": "Africa",
    "Superficie": "71,740",
    "Popolazione": "8,605,718",
    "Altitudine massima": "1948 m (Monte Bintumani)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "27/09/1961",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.32",
    "Rank Democracy Index": "102",
    "ISO 2": "SL",
    "ISO 3": "SLE"
  },
  {
    "Paese": "Singapore",
    "Capitale": "Singapore",
    "Bandiera": "https://flagcdn.com/w320/sg.png",
    "#": "157",
    "Continente": "Asia",
    "Superficie": "728",
    "Popolazione": "5,637,000",
    "Altitudine massima": "163 m (Bukit Timah)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "21/09/1965",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.18",
    "Rank Democracy Index": "68",
    "ISO 2": "SG",
    "ISO 3": "SGP"
  },
  {
    "Paese": "Siria",
    "Capitale": "Damasco",
    "Bandiera": "https://flagcdn.com/w320/sy.png",
    "#": "158",
    "Continente": "Asia",
    "Superficie": "185,180",
    "Popolazione": "22,125,249",
    "Altitudine massima": "2814 m (Monte Hermon)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.32",
    "Rank Democracy Index": "163",
    "ISO 2": "SY",
    "ISO 3": "SYR"
  },
  {
    "Paese": "Slovacchia",
    "Capitale": "Bratislava",
    "Bandiera": "https://flagcdn.com/w320/sk.png",
    "#": "159",
    "Continente": "Europa",
    "Superficie": "49,035",
    "Popolazione": "5,431,752",
    "Altitudine massima": "2655 m (Gerlachovský štít)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "19/01/1993",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.21",
    "Rank Democracy Index": "42",
    "ISO 2": "SK",
    "ISO 3": "SVK"
  },
  {
    "Paese": "Slovenia",
    "Capitale": "Lubiana",
    "Bandiera": "https://flagcdn.com/w320/si.png",
    "#": "160",
    "Continente": "Europa",
    "Superficie": "20,273",
    "Popolazione": "2,110,516",
    "Altitudine massima": "2864 m (Tricorno)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "22/05/1992",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.82",
    "Rank Democracy Index": "30",
    "ISO 2": "SI",
    "ISO 3": "SVN"
  },
  {
    "Paese": "Somalia",
    "Capitale": "Mogadiscio",
    "Bandiera": "https://flagcdn.com/w320/so.png",
    "#": "161",
    "Continente": "Africa",
    "Superficie": "637,657",
    "Popolazione": "17,597,511",
    "Altitudine massima": "2450 m (Monte Shimbiris)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "SO",
    "ISO 3": "SOM"
  },
  {
    "Paese": "Spagna",
    "Capitale": "Madrid",
    "Bandiera": "https://flagcdn.com/w320/es.png",
    "#": "162",
    "Continente": "Europa",
    "Superficie": "505,992",
    "Popolazione": "47,420,000",
    "Altitudine massima": "3718 m (Teide)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.13",
    "Rank Democracy Index": "21",
    "ISO 2": "ES",
    "ISO 3": "ESP"
  },
  {
    "Paese": "Sri Lanka",
    "Capitale": "Sri Jayawardenepura Kotte",
    "Bandiera": "https://flagcdn.com/w320/lk.png",
    "#": "163",
    "Continente": "Asia",
    "Superficie": "65,610",
    "Popolazione": "22,181,000",
    "Altitudine massima": "2524 m (Pidurutalagala)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.19",
    "Rank Democracy Index": "67",
    "ISO 2": "LK",
    "ISO 3": "LKA"
  },
  {
    "Paese": "Stati Federati di Micronesia",
    "Capitale": "Palikir",
    "Bandiera": "https://flagcdn.com/w320/fm.png",
    "#": "164",
    "Continente": "Oceania",
    "Superficie": "702",
    "Popolazione": "114,164",
    "Altitudine massima": "782 m (Monte Nanlaud)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "17/09/1991",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "FM",
    "ISO 3": "FSM"
  },
  {
    "Paese": "Stati Uniti d'America",
    "Capitale": "Washington D.C.",
    "Bandiera": "https://flagcdn.com/w320/us.png",
    "#": "165",
    "Continente": "Nord America",
    "Superficie": "9,833,517",
    "Popolazione": "333,287,557",
    "Altitudine massima": "6190 m (Monte Denali)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.85",
    "Rank Democracy Index": "28",
    "ISO 2": "US",
    "ISO 3": "USA"
  },
  {
    "Paese": "Sudafrica",
    "Capitale": "Pretoria",
    "Bandiera": "https://flagcdn.com/w320/za.png",
    "#": "166",
    "Continente": "Africa",
    "Superficie": "1,221,037",
    "Popolazione": "60,600,000",
    "Altitudine massima": "3450 m (Mafadi)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "07/11/1945",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.16",
    "Rank Democracy Index": "43",
    "ISO 2": "ZA",
    "ISO 3": "ZAF"
  },
  {
    "Paese": "Sudan",
    "Capitale": "Khartoum",
    "Bandiera": "https://flagcdn.com/w320/sd.png",
    "#": "167",
    "Continente": "Africa",
    "Superficie": "1,861,484",
    "Popolazione": "46,874,204",
    "Altitudine massima": "3042 m (Deriba Caldera)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "12/11/1956",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.46",
    "Rank Democracy Index": "162",
    "ISO 2": "SD",
    "ISO 3": "SDN"
  },
  {
    "Paese": "Sudan del Sud",
    "Capitale": "Juba",
    "Bandiera": "https://flagcdn.com/w320/ss.png",
    "#": "168",
    "Continente": "Africa",
    "Superficie": "644,329",
    "Popolazione": "10,913,164",
    "Altitudine massima": "3187 m (Kinyeti)",
    "Paesi confinanti": "6",
    "Data adesione ONU": "14/07/2011",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "SS",
    "ISO 3": "SSD"
  },
  {
    "Paese": "Suriname",
    "Capitale": "Paramaribo",
    "Bandiera": "https://flagcdn.com/w320/sr.png",
    "#": "169",
    "Continente": "Sud America",
    "Superficie": "163,820",
    "Popolazione": "618,040",
    "Altitudine massima": "1280 m (Julianatop)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "04/12/1975",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.79",
    "Rank Democracy Index": "48",
    "ISO 2": "SR",
    "ISO 3": "SUR"
  },
  {
    "Paese": "Svezia",
    "Capitale": "Stoccolma",
    "Bandiera": "https://flagcdn.com/w320/se.png",
    "#": "170",
    "Continente": "Europa",
    "Superficie": "450,295",
    "Popolazione": "10,521,556",
    "Altitudine massima": "2097 m (Kebnekaise)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "19/11/1946",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9.39",
    "Rank Democracy Index": "3",
    "ISO 2": "SE",
    "ISO 3": "SWE"
  },
  {
    "Paese": "Svizzera",
    "Capitale": "Berna",
    "Bandiera": "https://flagcdn.com/w320/ch.png",
    "#": "171",
    "Continente": "Europa",
    "Superficie": "41,285",
    "Popolazione": "8,775,760",
    "Altitudine massima": "4634 m (Punta Dufour)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "10/09/2002",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "9.32",
    "Rank Democracy Index": "5",
    "ISO 2": "CH",
    "ISO 3": "CHE"
  },
  {
    "Paese": "Tagikistan",
    "Capitale": "Dushanbe",
    "Bandiera": "https://flagcdn.com/w320/tj.png",
    "#": "172",
    "Continente": "Asia",
    "Superficie": "143,100",
    "Popolazione": "9,952,787",
    "Altitudine massima": "7495 m (Picco Ismail Samani)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.83",
    "Rank Democracy Index": "159",
    "ISO 2": "TJ",
    "ISO 3": "TJK"
  },
  {
    "Paese": "Tanzania",
    "Capitale": "Dodoma",
    "Bandiera": "https://flagcdn.com/w320/tz.png",
    "#": "173",
    "Continente": "Africa",
    "Superficie": "947,303",
    "Popolazione": "65,497,748",
    "Altitudine massima": "5895 m (Kilimangiaro)",
    "Paesi confinanti": "8",
    "Data adesione ONU": "14/12/1961",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.2",
    "Rank Democracy Index": "86",
    "ISO 2": "TZ",
    "ISO 3": "TZA"
  },
  {
    "Paese": "Thailandia",
    "Capitale": "Bangkok",
    "Bandiera": "https://flagcdn.com/w320/th.png",
    "#": "174",
    "Continente": "Asia",
    "Superficie": "513,120",
    "Popolazione": "71,601,103",
    "Altitudine massima": "2565 m (Doi Inthanon)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "16/12/1946",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.27",
    "Rank Democracy Index": "63",
    "ISO 2": "TH",
    "ISO 3": "THA"
  },
  {
    "Paese": "Timor Est",
    "Capitale": "Dili",
    "Bandiera": "https://flagcdn.com/w320/tl.png",
    "#": "175",
    "Continente": "Asia",
    "Superficie": "14,874",
    "Popolazione": "1,341,296",
    "Altitudine massima": "2963 m (Monte Ramelau)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "27/09/2002",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.03",
    "Rank Democracy Index": "46",
    "ISO 2": "TL",
    "ISO 3": "TLS"
  },
  {
    "Paese": "Togo",
    "Capitale": "Lomé",
    "Bandiera": "https://flagcdn.com/w320/tg.png",
    "#": "176",
    "Continente": "Africa",
    "Superficie": "56,785",
    "Popolazione": "8,848,696",
    "Altitudine massima": "986 m (Monte Agou)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "20/09/1960",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.99",
    "Rank Democracy Index": "121",
    "ISO 2": "TG",
    "ISO 3": "TGO"
  },
  {
    "Paese": "Tonga",
    "Capitale": "Nuku'alofa",
    "Bandiera": "https://flagcdn.com/w320/to.png",
    "#": "177",
    "Continente": "Oceania",
    "Superficie": "747",
    "Popolazione": "107,773",
    "Altitudine massima": "1033 m (Località senza nome a Kao)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "14/09/1999",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "TO",
    "ISO 3": "TON"
  },
  {
    "Paese": "Trinidad e Tobago",
    "Capitale": "Port of Spain",
    "Bandiera": "https://flagcdn.com/w320/tt.png",
    "#": "178",
    "Continente": "Sud America",
    "Superficie": "5,128",
    "Popolazione": "1,531,044",
    "Altitudine massima": "940 m (El Cerro del Aripo)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "18/09/1962",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "7.09",
    "Rank Democracy Index": "45",
    "ISO 2": "TT",
    "ISO 3": "TTO"
  },
  {
    "Paese": "Tunisia",
    "Capitale": "Tunisi",
    "Bandiera": "https://flagcdn.com/w320/tn.png",
    "#": "179",
    "Continente": "Africa",
    "Superficie": "163,610",
    "Popolazione": "12,356,117",
    "Altitudine massima": "1544 m (Jebel ech Chambi)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "12/11/1956",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.71",
    "Rank Democracy Index": "93",
    "ISO 2": "TN",
    "ISO 3": "TUN"
  },
  {
    "Paese": "Turchia",
    "Capitale": "Ankara",
    "Bandiera": "https://flagcdn.com/w320/tr.png",
    "#": "180",
    "Continente": "Asia/Europa",
    "Superficie": "783,562",
    "Popolazione": "85,279,553",
    "Altitudine massima": "5137 m (Monte Ararat)",
    "Paesi confinanti": "8",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.26",
    "Rank Democracy Index": "103",
    "ISO 2": "TR",
    "ISO 3": "TUR"
  },
  {
    "Paese": "Turkmenistan",
    "Capitale": "Ashgabat",
    "Bandiera": "https://flagcdn.com/w320/tm.png",
    "#": "181",
    "Continente": "Asia",
    "Superficie": "488,100",
    "Popolazione": "6,430,770",
    "Altitudine massima": "3139 m (Aýrybaba)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.66",
    "Rank Democracy Index": "161",
    "ISO 2": "TM",
    "ISO 3": "TKM"
  },
  {
    "Paese": "Tuvalu",
    "Capitale": "Funafuti",
    "Bandiera": "https://flagcdn.com/w320/tv.png",
    "#": "182",
    "Continente": "Oceania",
    "Superficie": "26",
    "Popolazione": "11,312",
    "Altitudine massima": "5 m (Località senza nome a Niulakita)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "05/09/2000",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "TV",
    "ISO 3": "TUV"
  },
  {
    "Paese": "Ucraina",
    "Capitale": "Kiev",
    "Bandiera": "https://flagcdn.com/w320/ua.png",
    "#": "183",
    "Continente": "Europa",
    "Superficie": "603,500",
    "Popolazione": "36,744,634",
    "Altitudine massima": "2061 m (Hoverla)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "24/10/1945",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.9",
    "Rank Democracy Index": "92",
    "ISO 2": "UA",
    "ISO 3": "UKR"
  },
  {
    "Paese": "Uganda",
    "Capitale": "Kampala",
    "Bandiera": "https://flagcdn.com/w320/ug.png",
    "#": "184",
    "Continente": "Africa",
    "Superficie": "241,038",
    "Popolazione": "47,249,535",
    "Altitudine massima": "5109 m (Monte Stanley)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "25/10/1962",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "4.49",
    "Rank Democracy Index": "98",
    "ISO 2": "UG",
    "ISO 3": "UGA"
  },
  {
    "Paese": "Ungheria",
    "Capitale": "Budapest",
    "Bandiera": "https://flagcdn.com/w320/hu.png",
    "#": "185",
    "Continente": "Europa",
    "Superficie": "93,030",
    "Popolazione": "9,683,000",
    "Altitudine massima": "1014 m (Kekes)",
    "Paesi confinanti": "7",
    "Data adesione ONU": "14/12/1955",
    "Tipo di regime": "Democrazia imperfetta",
    "Democracy Index": "6.51",
    "Rank Democracy Index": "54",
    "ISO 2": "HU",
    "ISO 3": "HUN"
  },
  {
    "Paese": "Uruguay",
    "Capitale": "Montevideo",
    "Bandiera": "https://flagcdn.com/w320/uy.png",
    "#": "186",
    "Continente": "Sud America",
    "Superficie": "176,215",
    "Popolazione": "3,422,794",
    "Altitudine massima": "514 m (Cerro Catedral)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "18/12/1945",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.67",
    "Rank Democracy Index": "15",
    "ISO 2": "UY",
    "ISO 3": "URY"
  },
  {
    "Paese": "Uzbekistan",
    "Capitale": "Tashkent",
    "Bandiera": "https://flagcdn.com/w320/uz.png",
    "#": "187",
    "Continente": "Asia",
    "Superficie": "447,400",
    "Popolazione": "36,024,946",
    "Altitudine massima": "4643 m (Khazret Sultan)",
    "Paesi confinanti": "5",
    "Data adesione ONU": "02/03/1992",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.1",
    "Rank Democracy Index": "146",
    "ISO 2": "UZ",
    "ISO 3": "UZB"
  },
  {
    "Paese": "Vanuatu",
    "Capitale": "Port Vila",
    "Bandiera": "https://flagcdn.com/w320/vu.png",
    "#": "188",
    "Continente": "Oceania",
    "Superficie": "12,189",
    "Popolazione": "326,740",
    "Altitudine massima": "1877 m (Monte Tabwemasana)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "15/09/1981",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "VU",
    "ISO 3": "VUT"
  },
  {
    "Paese": "Venezuela",
    "Capitale": "Caracas",
    "Bandiera": "https://flagcdn.com/w320/ve.png",
    "#": "189",
    "Continente": "Sud America",
    "Superficie": "912,050",
    "Popolazione": "28,301,696",
    "Altitudine massima": "4978 m (Pico Bolivar)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "15/11/1945",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.25",
    "Rank Democracy Index": "142",
    "ISO 2": "VE",
    "ISO 3": "VEN"
  },
  {
    "Paese": "Vietnam",
    "Capitale": "Hanoi",
    "Bandiera": "https://flagcdn.com/w320/vn.png",
    "#": "190",
    "Continente": "Asia",
    "Superficie": "331,210",
    "Popolazione": "98,186,856",
    "Altitudine massima": "3143 m (Fansipan)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "20/09/1977",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.62",
    "Rank Democracy Index": "133",
    "ISO 2": "VN",
    "ISO 3": "VNM"
  },
  {
    "Paese": "Yemen",
    "Capitale": "Sana'a",
    "Bandiera": "https://flagcdn.com/w320/ye.png",
    "#": "191",
    "Continente": "Asia",
    "Superficie": "527,968",
    "Popolazione": "33,696,614",
    "Altitudine massima": "3666 m (Jabal An-Nabi Shu'ayb)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "30/09/1947",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "1.95",
    "Rank Democracy Index": "155",
    "ISO 2": "YE",
    "ISO 3": "YEM"
  },
  {
    "Paese": "Zambia",
    "Capitale": "Lusaka",
    "Bandiera": "https://flagcdn.com/w320/zm.png",
    "#": "192",
    "Continente": "Africa",
    "Superficie": "752,618",
    "Popolazione": "20,017,675",
    "Altitudine massima": "2329 m (Mafinga Hills)",
    "Paesi confinanti": "8",
    "Data adesione ONU": "01/12/1964",
    "Tipo di regime": "Regime ibrido",
    "Democracy Index": "5.73",
    "Rank Democracy Index": "77",
    "ISO 2": "ZM",
    "ISO 3": "ZMB"
  },
  {
    "Paese": "Zimbabwe",
    "Capitale": "Harare",
    "Bandiera": "https://flagcdn.com/w320/zw.png",
    "#": "193",
    "Continente": "Africa",
    "Superficie": "390,757",
    "Popolazione": "15,993,524",
    "Altitudine massima": "2592 m (Monte Nyangani)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "25/08/1980",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "2.98",
    "Rank Democracy Index": "122",
    "ISO 2": "ZW",
    "ISO 3": "ZWE"
  },
  {
    "Paese": "Città del Vaticano",
    "Capitale": "Città del Vaticano",
    "Bandiera": "https://flagcdn.com/w320/va.png",
    "#": "194",
    "Continente": "Europa",
    "Superficie": "0.44",
    "Popolazione": "453",
    "Altitudine massima": "75 m (Piazza San Pietro)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "VA",
    "ISO 3": "VAT"
  },
  {
    "Paese": "Palestina",
    "Capitale": "Gerusalemme Est",
    "Bandiera": "https://flagcdn.com/w320/ps.png",
    "#": "195",
    "Continente": "Asia",
    "Superficie": "6,220",
    "Popolazione": "5,483,450",
    "Altitudine massima": "1030 m (Monte Nabi Yunis)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "Regime autoritario",
    "Democracy Index": "3.44",
    "Rank Democracy Index": "112",
    "ISO 2": "PS",
    "ISO 3": "PSE"
  },
  {
    "Paese": "Taiwan",
    "Capitale": "Taipei",
    "Bandiera": "https://flagcdn.com/w320/tw.png",
    "#": "196",
    "Continente": "Asia",
    "Superficie": "36,193",
    "Popolazione": "23,894,394",
    "Altitudine massima": "3952 m (Yu Shan)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "Democrazia completa",
    "Democracy Index": "8.78",
    "Rank Democracy Index": "12",
    "ISO 2": "TW",
    "ISO 3": "TWN"
  },
  {
    "Paese": "Isole Cook",
    "Capitale": "Avarua",
    "Bandiera": "https://flagcdn.com/w320/ck.png",
    "#": "197",
    "Continente": "Oceania",
    "Superficie": "236",
    "Popolazione": "13,228",
    "Altitudine massima": "658 m (Monte Te Manga)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "CK",
    "ISO 3": "COK"
  },
  {
    "Paese": "Niue",
    "Capitale": "Alofi",
    "Bandiera": "https://flagcdn.com/w320/nu.png",
    "#": "198",
    "Continente": "Oceania",
    "Superficie": "261",
    "Popolazione": "1,860",
    "Altitudine massima": "68 m (Talava Ridge)",
    "Paesi confinanti": "0",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "NU",
    "ISO 3": "NIU"
  },
  {
    "Paese": "Cipro del Nord",
    "Capitale": "Nicosia Nord",
    "Bandiera": "n.d.",
    "#": "199",
    "Continente": "Europa/Asia",
    "Superficie": "3,355",
    "Popolazione": "351,965",
    "Altitudine massima": "1024 m (Kyparissovouno)",
    "Paesi confinanti": "1",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "n.d.",
    "ISO 3": "n.d."
  },
  {
    "Paese": "Kosovo",
    "Capitale": "Pristina",
    "Bandiera": "https://flagcdn.com/w320/xk.png",
    "#": "200",
    "Continente": "Europa",
    "Superficie": "10,887",
    "Popolazione": "1,769,380",
    "Altitudine massima": "2660 m (Velika Rudoka)",
    "Paesi confinanti": "4",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "XK",
    "ISO 3": "UNK"
  },
  {
    "Paese": "Ossezia del Sud",
    "Capitale": "Tskhinvali",
    "Bandiera": "n.d.",
    "#": "201",
    "Continente": "Asia",
    "Superficie": "3,900",
    "Popolazione": "56,520",
    "Altitudine massima": "5193 m (Shkhara)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "n.d.",
    "ISO 3": "n.d."
  },
  {
    "Paese": "Repubblica di Abcasia",
    "Capitale": "Sukhumi",
    "Bandiera": "n.d.",
    "#": "202",
    "Continente": "Asia/Europa",
    "Superficie": "8,432",
    "Popolazione": "244,236",
    "Altitudine massima": "4046 m (Monte Dombai-Ulgen)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "n.d.",
    "ISO 3": "n.d."
  },
  {
    "Paese": "Sahara Occidentale",
    "Capitale": "El Aaiún",
    "Bandiera": "n.d.",
    "#": "203",
    "Continente": "Africa",
    "Superficie": "266,000",
    "Popolazione": "599,430",
    "Altitudine massima": "n.d.",
    "Paesi confinanti": "3",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "n.d.",
    "ISO 3": "n.d."
  },
  {
    "Paese": "Somaliland",
    "Capitale": "Hargheisa",
    "Bandiera": "n.d.",
    "#": "204",
    "Continente": "Africa",
    "Superficie": "176,120",
    "Popolazione": "6,200,000",
    "Altitudine massima": "2460 m (Shimbiris)",
    "Paesi confinanti": "3",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "n.d.",
    "ISO 3": "n.d."
  },
  {
    "Paese": "Transnistria",
    "Capitale": "Tiraspol",
    "Bandiera": "n.d.",
    "#": "205",
    "Continente": "Europa",
    "Superficie": "4,163",
    "Popolazione": "465,800",
    "Altitudine massima": "240 m (Monte Dzeržinskij)",
    "Paesi confinanti": "2",
    "Data adesione ONU": "n.d.",
    "Tipo di regime": "n.d.",
    "Democracy Index": "n.d.",
    "Rank Democracy Index": "n.d.",
    "ISO 2": "n.d.",
    "ISO 3": "n.d."
  }
] ;